"""add_task_is_notified_and_priority_fields

Revision ID: 24270b19651f
Revises: 2c4093aca04e
Create Date: 2025-10-21 19:35:21.716345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24270b19651f'
down_revision: Union[str, Sequence[str], None] = '2c4093aca04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_notified', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.String(), nullable=True))
    op.drop_column('tasks', 'reminder_time')
    op.drop_column('tasks', 'reminder_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reminder_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('reminder_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'is_notified')
    # ### end Alembic commands ###
